name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt ruff mypy pytest
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy .
      - name: Test
        run: pytest -q
      - name: Upload snapshot diffs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: snapshot-diffs-${{ matrix.python-version }}
          path: tests/__snapshots__
          if-no-files-found: ignore
